accountMapping:
  RD: RD
  SWM: SWM

R&D:
  - label: Agile Ceremonies
    value: agile
  - label: Product Development
    value: product_dev

SWM:
  - label: Bug Fix
    value: bug_fix
  - label: Support Work
    value: support
